#ifndef TSBINANCECLIENT_GLOBAL_H
#define TSBINANCECLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TSBINANCECLIENT_LIBRARY)
#  define TSBINANCECLIENT_EXPORT Q_DECL_EXPORT
#else
#  define TSBINANCECLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // TSBINANCECLIENT_GLOBAL_H
